# Use a Node.js base image
FROM node:14

# Set the working directory in the container
WORKDIR /Interface

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the UI code to the container
COPY . .

# Expose the port that Node will use
EXPOSE 7001

# Command to run the UI
CMD ["npm", "start"]
